spring.application.name=client
spring.mongodb.uri=${mongodb+srv://Nitinjobdekho:Nitin1402%40@jobdekho.h6xx5j8.mongodb.net/?appName=jobDekho}
spring.mongodb.database=jobDekho
server.port=${8081}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=auditforyou01@gmail.com
spring.mail.password=gmlxpabecxfdxbrl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
